### ISSUE TITLE
is say

### ISSUE THREAD

**Issue by a52948** [enijar/torrent-streaming#1]
Server error

**Comment by enijar** [comment]
@a52948 can you send the error you see?

**Comment by a52948** [comment]
I can't use sendgrid in my country, and I can't register a sendgrid account, and after disabling the mail environment variable, the following error occurs. Not disabling will also because I can fill in a wrong parameter. I use the docker deployment. Using npm is the same mistake
![image](https://github.com/enijar/torrent-streaming/assets/26563810/1b14533c-8379-4abc-b54e-4f8d609529d9)
![image](https://github.com/enijar/torrent-streaming/assets/26563810/147a39f4-a8ef-48e1-81a7-2d8a4990fe0c)

**Comment by enijar** [comment]
You can also login via the admin page. Visit the `/admin` page. Be sure to update the [server/src/config.ts](https://github.com/enijar/torrent-streaming/blob/main/server/src/config.ts#L19-L20) admin email and password. These values are generated with `bcrypt`

**Comment by a52948** [comment]
Because of the lack of CRT certificate, the service cannot be started with this book

**Comment by enijar** [comment]
Instead of disabling the email ENV. Can you build and run the image with fake email credentials? This will still work.

Build:

```shell
docker build server \
  --rm \
  -f server/Dockerfile \
  -t torrent-streaming/server \
  --build-arg NODE_ENV=production \
  --build-arg PORT=3000 \
  --build-arg API_URL=http://localhost:3000 \
  --build-arg APP_URL=http://localhost:8080 \
  --build-arg CORS_ORIGINS=http://localhost:3000,http://localhost:8080 \
  --build-arg BCRYPT_ROUNDS=12 \
  --build-arg DATABASE_HOST=127.0.0.1 \
  --build-arg DATABASE_NAME=torrent-streaming \
  --build-arg DATABASE_DIALECT=sqlite \
  --build-arg DATABASE_USERNAME=torrent-streaming \
  --build-arg DATABASE_PASSWORD=secret \
  --build-arg DATABASE_STORAGE=.cache/database.sqlite \
  --build-arg JWT_SECRET=secret \
  --build-arg EMAIL_PREVIEW=true \
  --build-arg EMAIL_SEND=false \
  --build-arg EMAIL_FROM=hello@example.com \
  --build-arg EMAIL_SMTP_HOST=smtp.sendgrid.net \
  --build-arg EMAIL_SMTP_PORT=587 \
  --build-arg EMAIL_SMTP_USERNAME=apikey \
  --build-arg EMAIL_SMTP_PASSWORD=secret
```

Run:

```shell
docker run --rm -p 3000:3000 torrent-streaming/server
```

**Comment by a52948** [comment]
I tried this operation you said, but it didn't work, so I tried disabling email, but I reported the same error! default password is "secret" ?

This is the container I built, put it on the hub.docker.com repository, using the default env you provided, you can try, I directly report the error when running. No issues were found at build time. "a52948/server and a52948/client"

**Comment by enijar** [comment]
Do you get the error when you build and run locally?

**Comment by a52948** [comment]
When building a container, npm warns that there is a problem with the version, but in the end the build succeeds, only a warning message, no error
